# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(560, 420)
        Register.setMinimumSize(QtCore.QSize(560, 420))
        Register.setMaximumSize(QtCore.QSize(560, 420))
        self.widget = QtWidgets.QWidget(Register)
        self.widget.setGeometry(QtCore.QRect(39, 29, 511, 321))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 0, 91, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_account = QtWidgets.QLabel(self.layoutWidget)
        self.label_account.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_account.setObjectName("label_account")
        self.verticalLayout.addWidget(self.label_account)
        self.label_password = QtWidgets.QLabel(self.layoutWidget)
        self.label_password.setMinimumSize(QtCore.QSize(80, 43))
        self.label_password.setMaximumSize(QtCore.QSize(80, 43))
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.label_passwordconfirm = QtWidgets.QLabel(self.layoutWidget)
        self.label_passwordconfirm.setMinimumSize(QtCore.QSize(80, 43))
        self.label_passwordconfirm.setMaximumSize(QtCore.QSize(80, 43))
        self.label_passwordconfirm.setObjectName("label_passwordconfirm")
        self.verticalLayout.addWidget(self.label_passwordconfirm)
        self.label_vrifinfo = QtWidgets.QLabel(self.layoutWidget)
        self.label_vrifinfo.setMinimumSize(QtCore.QSize(80, 43))
        self.label_vrifinfo.setMaximumSize(QtCore.QSize(80, 43))
        self.label_vrifinfo.setObjectName("label_vrifinfo")
        self.verticalLayout.addWidget(self.label_vrifinfo)
        self.label_gamename = QtWidgets.QLabel(self.layoutWidget)
        self.label_gamename.setMinimumSize(QtCore.QSize(80, 43))
        self.label_gamename.setMaximumSize(QtCore.QSize(80, 43))
        self.label_gamename.setObjectName("label_gamename")
        self.verticalLayout.addWidget(self.label_gamename)
        self.label_sex = QtWidgets.QLabel(self.layoutWidget)
        self.label_sex.setMinimumSize(QtCore.QSize(80, 43))
        self.label_sex.setMaximumSize(QtCore.QSize(80, 43))
        self.label_sex.setObjectName("label_sex")
        self.verticalLayout.addWidget(self.label_sex)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 0, 302, 251))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_account = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_account.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_account.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.verticalLayout_2.addWidget(self.lineEdit_account)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.lineEdit_passwordconfirm = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_passwordconfirm.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_passwordconfirm.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_passwordconfirm.setObjectName("lineEdit_passwordconfirm")
        self.verticalLayout_2.addWidget(self.lineEdit_passwordconfirm)
        self.lineEdit_vrifinfo = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_vrifinfo.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_vrifinfo.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_vrifinfo.setObjectName("lineEdit_vrifinfo")
        self.verticalLayout_2.addWidget(self.lineEdit_vrifinfo)
        self.lineEdit_gamename = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_gamename.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_gamename.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_gamename.setObjectName("lineEdit_gamename")
        self.verticalLayout_2.addWidget(self.lineEdit_gamename)
        self.layoutWidget2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(180, 250, 191, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_male = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_male.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_male.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_male.setObjectName("radioButton_male")
        self.horizontalLayout.addWidget(self.radioButton_male)
        self.radioButton_female = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_female.setMinimumSize(QtCore.QSize(0, 30))
        self.radioButton_female.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_female.setObjectName("radioButton_female")
        self.horizontalLayout.addWidget(self.radioButton_female)
        self.layoutWidget3 = QtWidgets.QWidget(Register)
        self.layoutWidget3.setGeometry(QtCore.QRect(220, 340, 202, 33))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_cancel = QtWidgets.QPushButton(self.layoutWidget3)
        self.Button_cancel.setMinimumSize(QtCore.QSize(96, 30))
        self.Button_cancel.setMaximumSize(QtCore.QSize(90, 30))
        self.Button_cancel.setObjectName("Button_cancel")
        self.horizontalLayout_2.addWidget(self.Button_cancel)
        self.Button_ok = QtWidgets.QPushButton(self.layoutWidget3)
        self.Button_ok.setMinimumSize(QtCore.QSize(96, 30))
        self.Button_ok.setMaximumSize(QtCore.QSize(96, 30))
        self.Button_ok.setObjectName("Button_ok")
        self.horizontalLayout_2.addWidget(self.Button_ok)
        self.layoutWidget.raise_()
        self.widget.raise_()

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "注册"))
        self.label_account.setText(_translate("Register", "用户名"))
        self.label_password.setText(_translate("Register", "密码"))
        self.label_passwordconfirm.setText(_translate("Register", "确认密码"))
        self.label_vrifinfo.setText(_translate("Register", "验证信息"))
        self.label_gamename.setText(_translate("Register", "昵称"))
        self.label_sex.setText(_translate("Register", "性别"))
        self.radioButton_male.setText(_translate("Register", "男"))
        self.radioButton_female.setText(_translate("Register", "女"))
        self.Button_cancel.setText(_translate("Register", "取消"))
        self.Button_ok.setText(_translate("Register", "提交"))

