# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Calvin/Downloads/study/Tedu/normal/project/game/test/reset_passwd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_reset_password(object):
    def setupUi(self, reset_password):
        reset_password.setObjectName("reset_password")
        reset_password.resize(560, 420)
        reset_password.setMinimumSize(QtCore.QSize(560, 420))
        reset_password.setMaximumSize(QtCore.QSize(560, 420))
        self.Button_checkaccount = QtWidgets.QPushButton(reset_password)
        self.Button_checkaccount.setGeometry(QtCore.QRect(190, 150, 100, 30))
        self.Button_checkaccount.setMinimumSize(QtCore.QSize(100, 30))
        self.Button_checkaccount.setMaximumSize(QtCore.QSize(100, 30))
        self.Button_checkaccount.setObjectName("Button_checkaccount")
        self.layoutWidget = QtWidgets.QWidget(reset_password)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 330, 200, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_cancel = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_cancel.setMinimumSize(QtCore.QSize(96, 30))
        self.Button_cancel.setMaximumSize(QtCore.QSize(96, 30))
        self.Button_cancel.setObjectName("Button_cancel")
        self.horizontalLayout_2.addWidget(self.Button_cancel)
        self.Button_ok = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_ok.setMinimumSize(QtCore.QSize(96, 30))
        self.Button_ok.setMaximumSize(QtCore.QSize(96, 30))
        self.Button_ok.setObjectName("Button_ok")
        self.horizontalLayout_2.addWidget(self.Button_ok)
        self.widget = QtWidgets.QWidget(reset_password)
        self.widget.setGeometry(QtCore.QRect(100, 30, 62, 94))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_account = QtWidgets.QLabel(self.widget)
        self.label_account.setMinimumSize(QtCore.QSize(0, 43))
        self.label_account.setMaximumSize(QtCore.QSize(50, 43))
        self.label_account.setObjectName("label_account")
        self.verticalLayout.addWidget(self.label_account)
        self.label_vrifinfo = QtWidgets.QLabel(self.widget)
        self.label_vrifinfo.setMinimumSize(QtCore.QSize(0, 43))
        self.label_vrifinfo.setMaximumSize(QtCore.QSize(16777215, 43))
        self.label_vrifinfo.setObjectName("label_vrifinfo")
        self.verticalLayout.addWidget(self.label_vrifinfo)
        self.widget1 = QtWidgets.QWidget(reset_password)
        self.widget1.setGeometry(QtCore.QRect(190, 30, 202, 101))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_account = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_account.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_account.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.verticalLayout_2.addWidget(self.lineEdit_account)
        self.lineEdit_vrifinfo = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_vrifinfo.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_vrifinfo.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_vrifinfo.setObjectName("lineEdit_vrifinfo")
        self.verticalLayout_2.addWidget(self.lineEdit_vrifinfo)
        self.widget2 = QtWidgets.QWidget(reset_password)
        self.widget2.setGeometry(QtCore.QRect(100, 200, 62, 94))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_password = QtWidgets.QLabel(self.widget2)
        self.label_password.setMinimumSize(QtCore.QSize(0, 43))
        self.label_password.setMaximumSize(QtCore.QSize(100, 43))
        self.label_password.setObjectName("label_password")
        self.verticalLayout_3.addWidget(self.label_password)
        self.label_passwordconfirm = QtWidgets.QLabel(self.widget2)
        self.label_passwordconfirm.setMinimumSize(QtCore.QSize(0, 43))
        self.label_passwordconfirm.setMaximumSize(QtCore.QSize(16777215, 43))
        self.label_passwordconfirm.setObjectName("label_passwordconfirm")
        self.verticalLayout_3.addWidget(self.label_passwordconfirm)
        self.widget3 = QtWidgets.QWidget(reset_password)
        self.widget3.setGeometry(QtCore.QRect(190, 200, 202, 101))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_4.addWidget(self.lineEdit_password)
        self.lineEdit_passwordconfirm = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_passwordconfirm.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_passwordconfirm.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_passwordconfirm.setObjectName("lineEdit_passwordconfirm")
        self.verticalLayout_4.addWidget(self.lineEdit_passwordconfirm)

        self.retranslateUi(reset_password)
        QtCore.QMetaObject.connectSlotsByName(reset_password)

    def retranslateUi(self, reset_password):
        _translate = QtCore.QCoreApplication.translate
        reset_password.setWindowTitle(_translate("reset_password", "找回密码"))
        self.Button_checkaccount.setText(_translate("reset_password", "找回密码"))
        self.Button_cancel.setText(_translate("reset_password", "取消"))
        self.Button_ok.setText(_translate("reset_password", "提交"))
        self.label_account.setText(_translate("reset_password", "用户名"))
        self.label_vrifinfo.setText(_translate("reset_password", "验证信息"))
        self.label_password.setText(_translate("reset_password", "新密码"))
        self.label_passwordconfirm.setText(_translate("reset_password", "确认密码"))

